###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: docker-mysql-datescourtes
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=Devbp25
        - MYSQL_DATABASE=dates
        - MYSQL_USER=kiwifunky
        - MYSQL_PASSWORD=Devbp25
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: docker-webserver-datescourtes
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-php-fpm-datescourtes
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-datescourtes
      ports:
        - '8080:80'
      environment:
        PMA_HOST: mysql